Add SDK
appwrite/awesome-appwrite pull request #35
Opened 2020-10-15 22:16 UTC by lenzfliker

2020-10-16 13:22 UTC, notnavindu approved these changes

2020-10-21 11:26 UTC, lenzfliker commented
@eldadfux

2020-10-21 13:54 UTC, eldadfux requested changes

2020-10-21 13:54 UTC, eldadfux commented on README.md
> +* [Appwrite Flutter SDK](https://github.com/appwrite/sdk-for-flutter)
Please add ` (beta)` with space after `[Appwrite Flutter SDK`

2020-10-21 13:54 UTC, eldadfux commented on README.md
> +* [Appwrite SDK for Go](https://github.com/appwrite/sdk-for-go)
The GO SDK is still a work in progress, please remove it.

2020-10-21 13:54 UTC, eldadfux commented on README.md
> +* [Appwrite Python SDK](https://github.com/appwrite/sdk-for-python)(beta)
Please add ` (beta)` with space after `[Appwrite Python SDK`

2020-10-21 13:54 UTC, eldadfux commented on README.md
> +* [Appwrite Ruby SDK](https://github.com/appwrite/sdk-for-ruby)(beta)
Please add ` (beta)` with space after `[Appwrite Ruby SDK`

2020-10-21 13:54 UTC, eldadfux commented on README.md
> +* [Appwrite Deno SDK](https://github.com/appwrite/sdk-for-deno)(beta)
Please add ` (beta)` with space after `[Appwrite Deno SDK`

2020-10-21 19:22 UTC, eldadfux approved these changes

2020-10-21 19:22 UTC, merged

2020-10-21 19:22 UTC, eldadfux commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like me to send you some cool Appwrite stickers and magnets! Please note that shipping might take longer times because of COVID19.

As a way of saying thank you, we have just invited you to join the Appwrite organization on GitHub. You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.