added new blog post - manage Appwrite data with Appsmith
appwrite/awesome-appwrite pull request #352
Opened 2021-10-30 16:11 UTC by imknight

manage Appwrite data with Appsmith

2021-10-30 16:45 UTC, TheLearneer requested changes
Found a small issue ✌️

2021-10-30 16:45 UTC, TheLearneer commented on README.md
> +* [Manage Appwrite data with Appsmith] (https://imknight.com/manage-appwrite-data-with-appsmith/)
```suggestion
* [Manage Appwrite data with Appsmith](https://imknight.com/manage-appwrite-data-with-appsmith/)
```

2021-10-31 00:28 UTC, imknight commented on README.md
> +* [Manage Appwrite data with Appsmith] (https://imknight.com/manage-appwrite-data-with-appsmith/)
noted & fixed. thanks @TheLearneer

2021-10-31 06:54 UTC, merged

2021-10-31 06:54 UTC, lohanidamodar commented
THANK YOU! All changes merged 🥳

Please reach out to `eldadfux` on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues) and help make Appwrite better :)