Feat jordi5107 blog
appwrite/awesome-appwrite pull request #372
Opened 2021-10-31 11:38 UTC by jordi5107

Added a new blog post on Dev.to on [What is AppWrite and who i setup in my project?](https://dev.to/jordi5107/what-is-appwrite-and-who-i-setup-in-my-project-3af)

Sorry for merge problems.

2021-10-31 13:21 UTC, TheLearneer reviewed
There seems to be a fanart commit alongside the blog commit.
Also it seems you removed some existing links. 😓

2021-10-31 19:47 UTC, jordi5107 commented
Sorry for that i think i fixed

2021-11-01 07:46 UTC, Meldiron requested changes
Let's increase the length of the article to give it more value. There is soooo much to write about

2021-11-01 18:44 UTC, jordi5107 commented
I have improved the post and added more content to it, I hope it is better now 🙂.

2021-11-05 14:23 UTC, Meldiron requested changes
Let's fix all `AppWrite` to `Appwrite` and correctly mark code blocks so we get syntax highlighting (its markdown feature supported by Dev.to)

2021-11-05 16:04 UTC, jordi5107 commented
Fix that things.

2021-11-16 15:37 UTC, jordi5107 commented
Any feedback?

2021-11-28 15:58 UTC, christyjacob4 requested changes
<img width="736" alt="Screenshot 2021-11-28 at 7 58 06 PM" src="https://user-images.githubusercontent.com/20852629/143775758-2a5a0e25-580b-430e-bf0e-33f95c26549c.png">

Please fix the title of your blog to use `Appwrite` and not `AppWrite`. 

Please address the merge conflict as well

2021-12-07 19:28 UTC, jordi5107 commented
Fixed

2021-12-19 18:59 UTC, christyjacob4 commented on README.md
> +* [What is AppWrite and who i setup in my project?](https://dev.to/jordi5107/what-is-appwrite-and-who-i-setup-in-my-project-3af)
```suggestion
* [What is Appwrite and who i setup in my project?](https://dev.to/jordi5107/what-is-appwrite-and-who-i-setup-in-my-project-3af)
```

2021-12-19 19:36 UTC, merged

2021-12-19 19:36 UTC, christyjacob4 commented
THANK YOU! All changes merged :partying_face:

Please reach out to me in Discord to claim your hacktoberfest swag!

As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord so that we can add you as a contributor to our organization.

Once added, you can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite membership badge will show up on your personal GitHub profile.