Appwrite-master
appwrite/awesome-appwrite pull request #397
Opened 2021-12-07 21:41 UTC by NeonSpork

2021-12-09 16:06 UTC, PineappleIOnic reviewed
This looks great! It will definitely improve the general readability of the runtimes and shine more light onto the resources the community has made for appwrite

2021-12-09 16:06 UTC, PineappleIOnic approved these changes

2021-12-10 16:41 UTC, adityaoberai requested changes
Love the work you've done here @NeonSpork 😄 
I've made some suggestions on the formatting of the title.
Do give them a glance once as well.

2021-12-10 16:41 UTC, adityaoberai commented on README.md
> +## Announcements and official blog posts
```suggestion
## Announcements and Official Blog Posts
```

2021-12-10 16:41 UTC, adityaoberai commented on README.md
> +## Learning resources
```suggestion
## Learning Resources 
```

2021-12-10 16:41 UTC, adityaoberai commented on README.md
> +### Getting started
```suggestion
### Getting Started
```

2021-12-10 16:41 UTC, adityaoberai commented on README.md
> +### Setup, customization and deploying
```suggestion
### Setup, Customization and Deployment
```

2021-12-10 16:41 UTC, adityaoberai commented on README.md
> +### Web development
```suggestion
### Web Development
```

2021-12-10 16:41 UTC, adityaoberai commented on README.md
> +### Mobile development
```suggestion
### Mobile Development
```

2021-12-10 16:41 UTC, adityaoberai commented on README.md
> +### Security and authentication
```suggestion
### Security and Authentication
```

2021-12-10 16:41 UTC, adityaoberai commented on README.md
> +### Appwrite services
```suggestion
### Appwrite Services
```

2021-12-10 16:41 UTC, adityaoberai commented on README.md
> +### golang
```suggestion
### Golang
```

2021-12-13 09:38 UTC, NeonSpork reviewed
@adityaoberai  I've made the changes to the capitalization of the sub-headers as requested, and additionally capitalized the respective entries in the links to content section at the top, 🙂

2021-12-14 12:53 UTC, adityaoberai requested changes
Just noticed a couple of anchor links that needed to be fixed here in the Table of Contents. Otherwise, looks like we're good!

2021-12-14 12:53 UTC, adityaoberai commented on README.md
> +    - [Setup, Customization and Deploying](#setup,-customization-and-deploying)
```suggestion
    - [Setup, Customization and Deploying](#setup-customization-and-deployment)
```

2021-12-14 12:53 UTC, adityaoberai commented on README.md
> +    - [Appwrite Services](#security-and-authorization)
```suggestion
    - [Appwrite Services](#appwrite-services)
```

2021-12-14 12:55 UTC, adityaoberai requested changes

2021-12-14 12:55 UTC, adityaoberai commented on README.md
> +    - [Security and Authorization](#security-and-authorization)
```suggestion
    - [Security and Authentication](#security-and-authentication)
```

2021-12-14 13:11 UTC, NeonSpork commented
> Just noticed a couple of anchor links that needed to be fixed here in the Table of Contents. Otherwise, looks like we're good!

Oops, I missed those! Good spot. Also agreed that it should be changed to authentication.

2021-12-14 13:26 UTC, adityaoberai approved these changes
Changes look good to merge now 👍

2021-12-14 14:36 UTC, merged

2021-12-14 14:36 UTC, adityaoberai commented
THANK YOU! All changes merged 🥳 

As a way of saying thank you, we would also love to invite you to **join the Appwrite organization** on GitHub. Please share your GitHub username with us on Discord so that we can add you as a contributor to our organization.

Once added, you can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite membership badge will show up on your personal GitHub profile.