Added a How to install Appwrite on a Linode cloud server.
appwrite/awesome-appwrite pull request #445
Opened 2022-10-18 16:47 UTC by Gregor-Davies

## What does this PR do?

This PR added a how to install appwrite on a linode cloud server tutorial.

## Test Plan

You can follow the steps in the tutorial.

## Related PRs and Issues

This PR is connected to the appwrite #4011 issue (https://github.com/appwrite/appwrite/issues/4011)

### Have you read the [Contributing Guidelines on issues

Yes

2022-10-26 21:11 UTC, gewenyu99 requested changes
Hi Gregor!

like the other PR, great writing! It's fun and humorous and I love the comics.

I'd like to suggest a quick grammar review, if possible, before I accept this PR. I think the writing is a little too loose for us to accept as is.

I think getting someone to proof read or using Grammarly are easy ways to clean this up a little. After that, I'd love to accept his awsome PR

Thanks a lot!!!

2022-10-26 21:11 UTC, gewenyu99 commented on README.md
> +* [How to install Appwrite on a Hetzner cloud server](https://dev.to/gregordavies/how-to-install-appwrite-on-a-hetzner-cloud-server-in-8-steps-1lan)
Ooops. Looks like you have a little something left over here!

2022-10-29 17:00 UTC, Gregor-Davies commented
> t writing! It's fun and humorous and I love the comics.
> 
> I'd like to suggest a quick grammar review, if possible, before I accept this PR. I think the writing is a little too loose for us to accept as is.
> 
> I think getting someone to proof read or using Grammarly are

Hello, I've tightened up my grammar with Grammarly. Hope this fixes all the mistakes :)

2022-10-31 14:51 UTC, gewenyu99 requested changes
It looks like you've added two links instead of one, please remove line # 147 

* [How to install Appwrite on a Hetzner cloud server](https://dev.to/gregordavies/how-to-install-appwrite-on-a-hetzner-cloud-server-in-8-steps-1lan)

2022-10-31 16:32 UTC, PineappleIOnic commented
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

2022-10-31 19:31 UTC, Gregor-Davies commented
> It looks like you've added two links instead of one, please remove line # 147
> 
> * [How to install Appwrite on a Hetzner cloud server](https://dev.to/gregordavies/how-to-install-appwrite-on-a-hetzner-cloud-server-in-8-steps-1lan)

Oops my bad fixed

2022-11-17 23:25 UTC, gewenyu99 approved these changes
Perfect, everything's tidied up!

Thank you for contributing @Gregor-Davies !

2022-12-19 18:30 UTC, merged

2022-12-19 18:30 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)