Appwrite + Preact blog
appwrite/awesome-appwrite pull request #450
Opened 2022-10-22 16:00 UTC by Sooraj-s-98

## What does this PR do?

A simple blog app built with Appwrite and Preact

## Test Plan

https://user-images.githubusercontent.com/52352285/197349002-ea649da2-d1a3-449d-be55-f0d04d65cfb4.mov
 
[Social](https://twitter.com/soorajsdevto)

## Related PRs and Issues

[issue ](https://github.com/appwrite/appwrite/issues/4252)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

yes

2022-10-22 16:25 UTC, Meldiron requested changes
Let's please do this tiny change, other than that, looks good to me.

2022-10-22 16:25 UTC, Meldiron commented on README.md
> +### PReact
```suggestion
### Preact
```

2022-10-22 16:27 UTC, Sooraj-s-98 commented on README.md
> +### PReact
sure

2022-10-22 16:30 UTC, Meldiron approved these changes
Looks great 🎉

2022-12-19 20:35 UTC, merged

2022-12-19 20:35 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)