Added a blogpost
appwrite/awesome-appwrite pull request #461
Opened 2022-10-29 17:16 UTC by Shruti700

Hacktoberfest 2022

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2022-10-31 16:18 UTC, PineappleIOnic commented
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

2022-10-31 20:55 UTC, gewenyu99 requested changes
Great post!

There's an unnecessary newline you've added. Please revert that change.

Other than that, great job!

2022-10-31 20:55 UTC, gewenyu99 commented on README.md
> +
Please revert this change

2023-01-27 21:46 UTC, christyjacob4 commented on README.md
> +
```suggestion
```

2023-01-27 21:46 UTC, christyjacob4 approved these changes

2023-01-27 21:46 UTC, merged

2023-01-27 21:46 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)

2023-01-28 04:35 UTC, Shruti700 commented
@christyjacob4 Thanks for acknowledging, but the invitation link is not working.