feat-4505-Build-‘Video-transcription-form‘-Demo-App!
appwrite/awesome-appwrite pull request #463
Opened 2022-10-30 14:06 UTC by ffex

## What does this PR do?

Added in the README.md the link to a Transcript This Demo source. This is a demo that implement "Transcript video form".
In input we put a Youtube link and the output is the transcription of the video.

## Test Plan

Check is the demo is correct and useful for the community.

## Related PRs and Issues

This is a demo for the  appwrite/appwrite#4505

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2022-10-31 16:18 UTC, PineappleIOnic commented
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

2023-01-09 13:38 UTC, christyjacob4 commented
@ffex please resolve the conflict

2023-01-18 17:57 UTC, ffex commented
Hi! sorry for the time! I'm pretty busy this months! Resolved :)

2023-02-03 15:05 UTC, adityaoberai requested changes
The application looks good to me. Just a little grammatical correction, and then we should be good to go 👍

2023-02-03 15:05 UTC, adityaoberai commented on README.md
> +* **Appwrite + Angular Transcript This** - A simple app to trascript Youtube videos from link. [Source Code](https://github.com/ffex/Transcript-This-Demo)
```suggestion
* **Appwrite + Angular Transcript This** - A simple app to transcribe Youtube videos from their links. [Source Code](https://github.com/ffex/Transcript-This-Demo)
```

Grammatical suggestion

2023-02-07 14:59 UTC, adityaoberai approved these changes

2023-02-07 14:59 UTC, merged

2023-02-07 15:00 UTC, adityaoberai commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)