add new framework django and the django-appwrite package description …
appwrite/awesome-appwrite pull request #476
Opened 2023-02-10 00:52 UTC by khashashin

[link to source code](https://github.com/khashashin/django-appwrite)

## What does this PR do?

This Pull Request (PR) adds a new category "django" and new information about the "django-appwrite" package. The new category "django" will provide a specific area for information related to the Django web framework, and the "django-appwrite" package information will give details about a package that provides integration between Django and the Appwrite Server.

The purpose of adding this information is likely to make it easier for users to find information related to Django and the integration between Django and the Appwrite Server. By having a separate category for Django and providing detailed information about the "django-appwrite" package, it will make it easier for users to understand the purpose and use of the package and how it can be used with Django.

This PR is likely to improve the overall organization and usability of the information related to Django and the Appwrite Server for users who want to integrate the two technologies.

## Test Plan

Nothing was changed except the README file.

2023-03-22 18:39 UTC, adityaoberai requested changes
Hey @khashashin 
Thank you so much for your contribution. We definitely appreciate your work on the package you've created.

Would it be alright if, for the time-being, we could shift this to the Python category? The reason I say so is because the Python category itself has some way to grow in our repository. Once it matures and warrants a framework-based breakup, we can then categorise it in a separate Django category.

Please let me know if that sounds alright.

2023-03-22 18:39 UTC, adityaoberai commented on README.md
> +* **Authenticate Appwrite User in Django** - A Django middleware to authenticate users with Appwrite. [Source Code](https://github.com/khashashin/django-appwrite)
Could we shift this to the Python category?

2023-03-22 22:33 UTC, khashashin commented
Hi @adityaoberai sure! Done! :)

2023-04-10 11:44 UTC, adityaoberai approved these changes
Thank you so much for your contribution, @khashashin! It looks great and I'm happy to go ahead and merge it in the repo 👍

2023-04-10 11:44 UTC, merged