Add Flutter Real-time Voting App
appwrite/awesome-appwrite pull request #483
Opened 2023-04-14 16:42 UTC by 0niel

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2023-05-08 14:16 UTC, adityaoberai requested changes
Thank you for the contribution @0niel!

I noticed that the project has all the [secret values explicitly mentioned in the repo](https://github.com/mirea-ninja/voting-app/blob/4e6f5f4c723a6b6af78eab808adfc737947de541/lib/constants.dart), which may make the application less secure.

Would you like to exclude this file from the repo and reset the values maybe? You can instead have an example file or a markdown with instructions on how to create this `constants.dart` file instead.

2023-06-16 10:49 UTC, adityaoberai commented
Hi @0niel 
Were you able to check the review I sent earlier and make the recommended changes?

2023-06-16 21:12 UTC, 0niel commented
> Hi @0niel Were you able to check the review I sent earlier and make the recommended changes?

Hi! I deleted the secrets, thank you!

I don't see much point in deleting the collection id in `constants.dart'. The application implies manually changing them in the source when required

2023-07-10 14:13 UTC, adityaoberai approved these changes

2023-07-10 14:13 UTC, merged