Add FoodMagic ✨
appwrite/awesome-appwrite pull request #76
Opened 2021-06-12 20:08 UTC by Sameerkash

2021-06-17 06:03 UTC, christyjacob4 commented on README.md
> +* **FoodMagic ✨** - An Augmented Reailty Food Delivery app built using Flutter and Appwrite ❤️. [Source Code](https://github.com/Sameerkash/FoodMagic)
I'd recommend you to add this under the 30DaysOfAppwrite section along with the other projects.

2021-06-17 06:03 UTC, christyjacob4 requested changes
Please address the comments

2021-06-18 05:59 UTC, christyjacob4 requested changes
Please remove the extra line here :slightly_smiling_face:

2021-06-18 05:59 UTC, christyjacob4 commented on README.md
> +
```suggestion
```

2021-06-22 08:31 UTC, Sameerkash commented
@christyjacob4 could you take a look?

2021-06-28 05:11 UTC, christyjacob4 approved these changes

2021-06-28 05:18 UTC, merged

2021-06-28 05:18 UTC, eldadfux commented
Great work @Sameerkash ❤️

2021-06-28 05:43 UTC, Sameerkash commented
Thanks @eldadfux 
I'll be contributing more soon <3